### PR TITLE
CI: run, take screenshot and compare with master screenshot

### PR DESCRIPTION
**Pull request by mikhailnov**
Please test `./util/test.sh` on you PC, is `[ "$screenshots_diff_value" -le 8000 ]` a reliable comparison?
If yes, then it can be added to CI

### CODE REVIEW

**Comment by mikhailnov** [comment]
PulseAudio probably has to be ran first in CI

**Comment by wwmm** [comment]
`test.sh` does not work in my computer
```
Temp dir: /tmp/tmp.kENWsEHOBd
Random DISPLAY = 67
./test.sh: line 61: Xephyr: command not found

(process:4803): Gtk-WARNING **: 22:06:11.207: Locale not supported by C library.
	Using the fallback 'C' locale.

(pulseeffects:4803): Gtk-WARNING **: 22:06:11.209: cannot open display: :67
pulseeffects did not start in 10 seconds, exiting with error!
./test.sh: line 29: kill: (4803) - No such process
./test.sh: line 29: kill: (4802) - No such process
```
I also have no idea if this is the property way to compara images... In any case now I am wondering if it is even possible to do this kind of test in circleci as the configuration is right now. The arch Linux image I am using probably does not have a desktop installed. And even if we use an image that has one I am not so sure they are doing graphical login. They may not have a Xorg instance running. I have to research a little about how to handle this in circleci.

**Comment by mikhailnov** [comment]
Install Xephyr from Arch repos ;-) See a comments in test.sh with a list of dependencies.
An Xorf session is not necessary, a headless Xvfb will be ran, just Xfvb and some core X libraries have to be installed

**Comment by mikhailnov** [comment]
It should work in CI if pulseaudio is started manually and if variable PE_BIN=path to builded PE executable is set (as described how to run from source in the wiki)

**Comment by wwmm** [comment]
Of course. I did not even think about trying to install the packages XD My head was somewhere else XD Now I can see the window and this is printed in the terminal
```
Temp dir: /tmp/tmp.30kjmtcILx
Random DISPLAY = 27

(process:7167): Gtk-WARNING **: 22:27:18.213: Locale not supported by C library.
	Using the fallback 'C' locale.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
Errors from xkbcomp are not fatal to the X server
```

**Comment by mikhailnov** [comment]
You should get `Graphical test: OK`

**Comment by wwmm** [comment]
After taking look at the code I realized this is what should have happened. But it doesn't print any of the graphical messages. The window opens and after some time it closes on its on. I know that the script is getting at least ot the line where `scrot` is ivoked because I had an error when this package was not installed. But it doesn't seem to be going much far than that.

**Comment by wwmm** [comment]
By the way I had to enable in circleci builds for pull requests. IT does not do that by default. Now it is working
Screenshot from 2019-05-21 22-55-30
Screenshot from 2019-05-21 22-58-33

While doig merge requests for Pulseaudio I noticed that gitlab does that for them. It was really cool. Nice to have this here too :D

**Comment by mikhailnov** [comment]
It must not print anything graphical, it just opens the window, wait for `SLEEP_TIME` which defaults to 10 second, make a screenshot, compare it with the master screenshot and close the window. Outputs either `Graphical test: OK` or `Graphical test: FAIL !!!`

if you don't get it, then the scripts stops somewhere before that die to using `set -e`, run it as `bash -x test.sh` to understand where it stops

**Comment by wwmm** [comment]
I did some tests by printing strings with `echo` and the script is getting stuck at this line:
```
screenshots_diff_value="$(compare -metric ae "${tmp_dir}/master_screenshot_reduced.png" "${tmp_dir}/current_screenshot_cropped.png" null: 2>&1)"
```
When I execute `bash -x ./util/test.sh` that is what is printed
```
+ set -e
+ export LANG=c
+ LANG=c
++ pwd
++ awk -F / '{print $NF}'
+ '[' pulseeffects = util ']'
+ dir0=/home/wallace/myfiles/code/cpp/pulseeffects
+ PE_BIN=pulseeffects
+ export -f cleanup
+ trap cleanup EXIT
+ graphical_run_test
+ '[' -n :1 ']'
+ X_SERVER=Xephyr
+ X_SERVER=Xephyr
+ export GTK_THEME=Adwaita:light
+ GTK_THEME=Adwaita:light
++ mktemp -d
+ tmp_dir=/tmp/tmp.d1PN6rx3D9
+ mkdir -p /tmp/tmp.d1PN6rx3D9
+ echo 'Temp dir: /tmp/tmp.d1PN6rx3D9'
Temp dir: /tmp/tmp.d1PN6rx3D9
+ rm -fvr '/tmp/tmp.d1PN6rx3D9/*'
+ virt_display=49
+ echo 'Random DISPLAY = 49'
Random DISPLAY = 49
+ case "$X_SERVER" in
+ echo 14717
+ export DISPLAY=:49
+ DISPLAY=:49
+ Xephyr -br -ac -noreset -screen 1024x720 :49
+ echo 14718
+ SLEEP_TIME=10
+ sleep 10
+ pulseeffects

(process:14718): Gtk-WARNING **: 23:07:43.311: Locale not supported by C library.
	Using the fallback 'C' locale.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
Errors from xkbcomp are not fatal to the X server
+ awk '{print $NF}'
+ grep -v 'grep '
+ grep -q 'pulseeffects$'
+ ps aux
+ scrot --quality 100 /tmp/tmp.d1PN6rx3D9/current_screenshot_full.png
+ MASTER_SCREENSHOT=/home/wallace/myfiles/code/cpp/pulseeffects/images/master_screenshot_test.png
+ '[' '!' -f /home/wallace/myfiles/code/cpp/pulseeffects/images/master_screenshot_test.png ']'
+ convert +dither -colors 2 /home/wallace/myfiles/code/cpp/pulseeffects/images/master_screenshot_test.png /tmp/tmp.d1PN6rx3D9/master_screenshot_reduced.png
+ convert +dither -colors 2 /tmp/tmp.d1PN6rx3D9/current_screenshot_full.png /tmp/tmp.d1PN6rx3D9/current_screenshot_cropped.png
++ compare -metric ae /tmp/tmp.d1PN6rx3D9/master_screenshot_reduced.png /tmp/tmp.d1PN6rx3D9/current_screenshot_cropped.png null:
+ screenshots_diff_value=257153
+ cleanup
+ set +e +f
+ read -r line
++ cat /tmp/tmp.d1PN6rx3D9/pulseeffects.pid /tmp/tmp.d1PN6rx3D9/X-server.pid
+ kill 14718
+ read -r line
+ kill 14717
+ read -r line
+ '[' -z '' ']'
+ rm -fr /tmp/tmp.d1PN6rx3D9/current_screenshot_cropped.png /tmp/tmp.d1PN6rx3D9/current_screenshot_full.png /tmp/tmp.d1PN6rx3D9/master_screenshot_reduced.png /tmp/tmp.d1PN6rx3D9/pulseeffects.pid /tmp/tmp.d1PN6rx3D9/X-server.pid
```

**Comment by mikhailnov** [comment]
`screenshots_diff_value=257153`
it means that screenshots differ too much, try running with `NO_CLEANUP=1 bash -x test.sh`, then it will not `rm` `/tmp/...`, then look at the screenshots that are saved there, 257153 is something like thay are completely different from what is needed.

**Comment by mikhailnov** [comment]
It seems that running PulseAudio in a CI docker container will be trickier than I thought, but that should be possible

**Comment by wwmm** [comment]
Reduced master screenshot
master_screenshot_reduced

Current screenshot cropped
current_screenshot_cropped

They are quite different. One of the reasons is that the window opened by the script is not enough to show PE window completely... Comparing screenshots with master doesn't seem to be a reliable method. I do not update those images often. So this kind of error may come back from time to time even if I find a way to make the script show the whole PE window.

**Comment by mikhailnov** [comment]
Where was `Current screenshot cropped` taken: in Xephyr or Xfvb? With code from https://github.com/wwmm/pulseeffects/pull/512 there is a seperate screenshot for Xfvb with a smaller size to reduce difference. Yours was probably taken in Xephyr. You may set `X_SERVER=Xfvb`. And in Docker container not all effects get loaded, so in https://github.com/wwmm/pulseeffects/pull/512 there is a seperate master screenshot which was taken inside container

**Comment by mikhailnov** [comment]
The difference value must be experimentally found so that small changes like adding new effects do not break the test.

**Comment by wwmm** [comment]
Probably in `Xephyr`. The script crashes if this one is not installed and `Xfvb` is not installed. And installing `xorg-server-xvfb` made no difference.

I will try to force Xfvb.

**Comment by wwmm** [comment]
The window does not open with `Xvfb`
```
wallace@wwmm ~/myfiles/code/cpp/pulseeffects $ env X_SERVER=Xvfb ./util/test.sh
Temp dir: /tmp/tmp.X3HOgD9gUw
Random DISPLAY = 30
Using Xvfb X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.

(process:8029): Gtk-WARNING **: 11:58:54.636: Locale not supported by C library.
	Using the fallback 'C' locale.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
Errors from xkbcomp are not fatal to the X server
```

**Comment by wwmm** [comment]
Ah... In Xvfb it will show nothing. Ok XD

**Pull request merged**
