### PR TITLE
revert moving to dists/ and add itstool

### PR DESCRIPTION
**Pull request by mikhailnov**

### CODE REVIEW

**Comment by wwmm** [comment]
I forgot about that. Honestly this debian behavior is little annoying :P

**Comment by mikhailnov** [comment]
It's annoying because debian building tools use the source code from inside this git repo, but PKGBUILD redownloads the code from git to its own directory, as I've understood, so for him it doesn't matter where the source code is located.

**Comment by wwmm** [comment]
No problems.

Does the `itstool` add something new? I did not build the package with this dependency and I  did not notice anything unusual

**Comment by wwmm** [comment]
It is already installed in my system. So maybe meson used it before and I did not see

**Comment by mikhailnov** [comment]
https://launchpadlibrarian.net/379713980/buildlog_ubuntu-cosmic-amd64.pulseeffects_4.1.9-5-git20180723~cosmic1_BUILDING.txt.gz

```
Running custom install script '/usr/bin/python3 /usr/bin/meson --internal yelphelper install --subdir=help --id=pulseeffects --installdir=share/help --sources=bassenhancer.page@@compressor.page@@deesser.page@@exciter.page@@filter.page@@gate.page@@index.page@@limiter.page@@loudness.page@@multibandcompressor.page@@multibandgate.page@@reverb.page@@stereoenhancer.page@@stereotools.page@@maximizer.page@@crossfeed.page@@equalizer.page@@pitch.page@@webrtc.page@@crystalizer.page@@convolver.page@@settingsmenu.page@@general.page@@spectrum.page@@pulseaudio.page@@testsignals.page@@calibrationmic.page@@enableapp.page@@effectsorder.page@@userpresets.page@@advancedinfo.page --symlinks=true --media=figures/mainwindow.png@@figures/effectsorder.png@@figures/enableapp.png@@figures/settingsmenu.png@@figures/userpresets.png@@figures/advancedinfo.png'Traceback (most recent call last):
  File "/usr/bin/meson", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/usr/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 379, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 316, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 232, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/dist-packages/mesonbuild/scripts/yelphelper.py", line 128, in run
    merge_translations(build_subdir, abs_sources, langs)
  File "/usr/lib/python3.6/dist-packages/mesonbuild/scripts/yelphelper.py", line 60, in merge_translations
    ] + sources)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'itstool': 'itstool'

FAILED: meson-install 
/usr/bin/python3 /usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by wwmm** [comment]
Ok. Good to know :-)

**Comment by mikhailnov** [comment]
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/meson&id=d1a895901cb6f737b143b50e82815723d1958481
starting from 0.47 meson has self-tests that use itstool, but as `checkdepends` in Arch

**Pull request merged**
