### PR TITLE
RNNoise redesigned and UI changes

### PR DESCRIPTION
**Pull request by Digitalone1**
Redesigned RNNoise UI a bit: model list frame is only visible when one or more models are added.

Then used ellipsize to limit string labels, so deleted the custom methods I previously added.

### CODE REVIEW

**Comment by wwmm** [comment]
I don't  know if it is only me but the file name label after the buttons is a little weird XD

**Comment by Digitalone1** [comment]
> I don't know if it is only me but the file name label after the buttons is a little weird XD

Can be changed. It seemed better to me when the file name too long is truncated to the right. 

Schermata del 2020-11-21 21-42-43

Can be modified if you want.

**Comment by wwmm** [comment]
I prefer the old widget order XD

**Comment by wwmm** [comment]
The problem with the current order is that my eyes always go to the "remove button" first instead of the file name label XD

**Comment by Digitalone1** [comment]
I'll change it.

**Pull request merged**
