### PR TITLE
fix Debian dependencies - 2 

### PR DESCRIPTION
**Pull request by mikhailnov**
additional fixes for https://github.com/wwmm/pulseeffects/issues/111

### CODE REVIEW

**Comment by AsavarTzeth** [comment]
May I suggest something? At this rate, perhaps it is better that you wait longer and do more testing in your fork before you do a pull request.

No offence meant, but I just don't want to see @wwmm spending too much time managing pull requests and issues related to this.

**Comment by mikhailnov** [comment]
yes, I agree with you. Arch dependencies confused me because those packages are splitted to many more in Debian.

**Comment by AsavarTzeth** [comment]
There is no shame in making a misstake or being confused :)

Just take your time. It is always better to catch mistakes or issues earlier and get it right. It will save not only your time, but others as well and serve you well in the long run.

Another suggestion is, when you get the time, to perhaps try and get this into Debian. That way you will get advice and reviews by the Debian community in the process. I am sure they will be able to offer a great deal of help.

**Comment by mikhailnov** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881224 (I tried submitting it yesterday, but Debian bug submitting system did not accept it for some reasons)

**Pull request closed without merging**
