### PR TITLE
v4.2.1 deb and UI changes

### PR DESCRIPTION
**Pull request by mikhailnov**
* v4.2.1 debian package
* `gstreamer1.0-autogain-pulseeffects` package
* updated Russian localization
* you forgot to mansion `libebur128-dev` as a new build dependency 

* changes to UI: I tried to make the new 'Auto Gain' UI better understandable; did not update any .po files except ru.po, they should be updated after this change

deepinscreenshot_pulseeffects_20180729145707
deepinscreenshot_pulseeffects_20180729145418

### CODE REVIEW

**Comment by wwmm** [comment]
I cherry picked the commits that were not related to the auto gain. The interface gets too verbose with these changes. It also defeats the purpose of having written the help in the manual. And different number of lines between neighbor labels is too striking to the eyes. 

If for some reason you think the user is not going to open the help or be able to find the auto gain entry this could be added as a tooltip shown when the mouse is over the widget.

**Comment by wwmm** [comment]
I am not against make the ui more user friendly whenever it is reasonable to do so and I understand it is not optimal to the user with less technical knowledge. But no audio equipment or plugin out there(be it for windows, linux or mac) has so much text in its interface. I agree with them in that decision. Although not perfect tooltips are a decent middle ground here for most of the users.

**Comment by mikhailnov** [comment]
Plugins are made for professional audio engineers, not other people. As pulseeffects is not made for professional audio processing and is opensource, we can try making it friendlier...
Tooltips do not solve the problem 'looking at the UI and do not understand anything', but still better than anything

**Comment by mikhailnov** [comment]
Maybe move on/off button into the bottom to prevent UI from being verbose on window resize?

**Comment by mikhailnov** [comment]
(it will be a bit strange)

**Comment by wwmm** [comment]
It will be very strange XD

**Comment by mikhailnov** [comment]
or it's possible to make a general title for multiple controls and leave shorts names of each control, it will use free space and prevent text duplication (the same text is duplicated in my variant)

**Comment by mikhailnov** [comment]
e.g.
Title for 3 controls: `Influence of measurements with different integration time`
control 1: `Momentary`
control 2: `Short term`
control 3: `Integrated value`
and move control 4 `Target` to separate line with text `Target` on the left from control, not above it

**Comment by mikhailnov** [comment]
`Weights` will be a word that just gives a general title for the group and does not help to better understand what they do

**Comment by mikhailnov** [comment]
Here are some suggestions from other people:
https://vk.com/wall-114916478_314164?reply=314174

**Comment by wwmm** [comment]
I still think it is better to have less text. To me the ui only gets more confusing to read with long lines of text there. Another problem of having long texts is that there isn't space to do this in all of them. The multi band versions of the gate and the compressor are examples of interfaces that are already crowded. It seems odd to me to have a few plugins with lots of text and others only with keywords.

The proposal to have the enable button to the right is not bad but I prefer to have this button in the same position in all plugins interface.

I will stick to short texts
screenshot from 2018-07-29 14-35-55

**Comment by mikhailnov** [comment]
Well, the meaning of 'Weights' is clear only after reading help... Weights in what is unclear

**Pull request closed without merging**
