### PR TITLE
add run in background option

### LINKED ISSUE #920: close pulseeffects service from gui
`pulseeffects -q` has no graphical equivalent

suggest `gtk_application_set_app_menu`

### PR DESCRIPTION
**Pull request by violetmage**
naive attempt

Fixes #920

### CODE REVIEW

**Comment by wwmm** [comment]
Without a `enable-run-in-background` key defined in the schema `com.github.wwmm.pulseeffects`  this is probably going to fail in some situations.

**Comment by violetmage** [comment]
gtk new for me :)

**Comment by wwmm** [comment]
I finally had time to take a look at this again. After cloning you repository I ran the command `glib-compile-schemas data/schemas/` inside the folder `pulseeffects` and there was an error:
```
data/schemas/com.github.wwmm.pulseeffects.gschema.xml:14:1  Error on line 14 char 1: attribute 'tybe' invalid for element 'key'.  This entire file has been ignored.
data/schemas/com.github.wwmm.pulseeffects.spectrum.gschema.xml:44:1  Error on line 44 char 1: <enum id='com.github.wwmm.pulseeffects.spectrum.type.enum'> not (yet) defined..  This entire file has been ignored.
```

It is probably a simple mistake in when editing the xml. At this moment the time I have to spend in this project is going to the gtk4 branch. Eventually I will add this functionality there.

**Comment by violetmage** [comment]
indeed, "b" != "p"

**Comment by wwmm** [comment]
Compilation error:
```
../src/general_settings_ui.cpp: In constructor ‘GeneralSettingsUi::GeneralSettingsUi(Gtk::Grid::BaseObjectType*, const Glib::RefPtr<Gtk::Builder>&, Application*)’:
../src/general_settings_ui.cpp:123:46: error: ‘enable_run_in_background’ was not declared in this scope
  123 |   settings->bind("enable-run-in-background", enable_run_in_background, "active", flag);
```

What is missing in this case is defining the variable `enable_run_in_background`. Just defining the id in the xml is not enough. A good place to define this variable would be this https://github.com/violetmage/pulseeffects/blob/4a1f0cf68d0e4f36c64d03706bf7428c447b7df5/include/general_settings_ui.hpp#L53

**Comment by violetmage** [comment]
of course, am silly :)

many thanks for help

**Comment by wwmm** [comment]
Implemented in our gtk4 branch

**Pull request closed without merging**
