### PR TITLE
Update com.github.wwmm.pulseeffects.appdata.xml.in

### PR DESCRIPTION
**Pull request by har9862**
* Added releases info for the last couple of releases
* Added OARS

### CODE REVIEW

**Comment by wwmm** [comment]
Thanks!

**Comment by AsavarTzeth** [comment]
I actually have a more extensive version of this, which I have maintained for a little while now. In time I did plan to ask you if you wish to maintain it upstream.

This though, causes issues for me. I have to ask, are you planning on maintaining this yourself from now on? It has to be included prior to tagging each release. Otherwise this just made my maintenance of the Flatpak a great deal lot harder.

Now as for the changes themselves I see multiple issues. First of have you verified this against `appstreamcli validate --pedantic` and `appstream-util validate-strict` (or at least `appstream-util validate`)? It seems mostly correct, but there are a few issues.

Lastly, the OARS data seems completely invalid. There is no data at all, just an empty tag? Again `appstreamcli` seems to react on this.

I recommend you look at at my patches:

- https://github.com/AsavarTzeth/pulseeffects/commit/99ce9cb8621ccfa20d7e97a9f49c351572c3eba1
- https://github.com/AsavarTzeth/pulseeffects/commit/d61a54c18e8c686cef07369ae50381947d0b22e8

Those have been in use for a while now on Flathub and it would probably be wiser to just use those instead. That is if you wish to maintain this yourself, which would certainly be welcome.

**Comment by wwmm** [comment]
I never thought about this file before receiving this pull request. So I was not aware that it had to be validated by appstream tools. I was also not aware you had been patching the flatpak package with this. Sorry :) If you have more extensive versions it is better to use the ones you have

Is flatpak the only one making use of appstream data or things like gnome and kde software center also make use of it? If there is use outside of flatpak it makes sense to maintain this info here.

Although I don't really think it is a problem to update this file and the changelog before each release I still wonder if there is a way to somehow to automate the creation of one of the files. Something like creating a custom meson build target that executes a script that would generate one of the files.

**Comment by AsavarTzeth** [comment]
Well I feel it is also my fault for never taking the time to mention it. In a way this pull request was a great way to force my hand.

All frontends pretty much use AppStream appdata, i.e GNOME Software, KDE Discover and the Flathub webb frontend.

Now with the release information specifically the advantage is tjat flatpak is then able to display the version.

About automation, I have tried many many times. The thing that is very difficult to do in a safe and reliable way with XML. Based on my attempts, it is possible, as long as you skip the description.

The problem with the description isn't so much XML as reliably parsing the current changelog. Adding a more parsable file, only for release descriptions, sort of defeats the idea. It just moves the issue.

Anyhow the current changelog isn't really suitable, since its a bit to technical and mentions some things that end users don't need to care about. It also fails some appstream-glib specific validations like the 100 char max per list item.

So if you're happy with just version and date (the most important parts), yes I could automate it.

I even made a script way back for this, which I could adjust for meson.

I could also toss in some appstream validation tests that run with meson.

**Comment by AsavarTzeth** [comment]
Well for what it is your changelog is mostly fine and informative to myself. I am just saying it may not all be something you would show in GNOME Software, or for comparison, Google Play or the Apple App Store.

I tried adjusting it for the audience, for a while. But it got too tedius; well at least with daily releases :P

I don't think descriptions would be overwritten. The automated part basicly would just add one or two lines to the top of the releases (the order matters). You could then add things in between the opening and closing tags.

As long as it first checks if a release already exists it should be fine. I will verify this when I get home, which is soon.

**Comment by wwmm** [comment]
Hahaha That is what I thought. It would be tedious to rewrite everything for non technical users :D

I think that we will have less often releases for a while. I don't have any plans in my mind and at this moment I don't know if it is even possible to do what is asked in #295 and #288. So the next updates will happen only if there is a bug to fix or if people send updated translations(or updated things like appstream info)

**Pull request merged**
