### PR TITLE
update debian/chengelog with newer versions

### PR DESCRIPTION
**Pull request by mikhailnov**
also added the result of running ```mk-build-deps --install debian/control``` to .gitignore

### CODE REVIEW

**Comment by mikhailnov** [comment]
\+ Fix https://github.com/wwmm/pulseeffects/issues/137

**Comment by wwmm** [comment]
In case you have not done it yet add Calf Studio plugins and the Lilv library as dependencies. They are not mandatory for PE to work but users wanting to try the exciter and the bass enhancer will not be able to do so without these packages

**Comment by mikhailnov** [comment]
Ok. calf-plugins and liblilv-0-0 will be added.

**Comment by wwmm** [comment]
It is not the calf that uses ladspa but the one that uses LV2. This is the package in Arch Linux [https://www.archlinux.org/packages/community/x86_64/calf/](https://www.archlinux.org/packages/community/x86_64/calf/)

**Pull request merged**
